server:
  port: 8080
spring:
  application:
    name: cupide
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/redis_Test?useSSL=false&serverTimezone=UTC&AllowPublicKeyRetrieval=true
    username: root
    password: 12345678
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  data:
    redis:
      host: localhost
      port: 6380
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      database: 1
mybatis-plus:
  type-aliases-package: com.cupide.entity # 别名扫描包
logging:
  level:
    com.cupide: debug